### ISSUE TITLE
Per miner/user stats missing

### ISSUE THREAD

**Issue by Rav3nPL** [hardcpp/P2PoolExtendedFrontEnd#1]
There is no stats for user/miner, only for node.

**Comment by hardcpp** [comment]
i didnt have redisigned this page but graps.html exist again.
i will make this in few hour.

look my better p2pool interface ltc.wincoin.com

**Comment by hardcpp** [comment]
i start working on it :)

**Comment by Rav3nPL** [comment]
Clicking on "Graph" on top: http://rav3n.dtdns.net:9332/static/#about
Clicking on "graph" aside of "last blocks" - nothing, but when mouse over it it shows correct http://rav3n.dtdns.net:9332/static/graphs.html and I can open it in new window/tab using RMB.
I use windows/firefox.

**Comment by hardcpp** [comment]
Done tell me if it's better

**Comment by hardcpp** [comment]
Live ex http://94.23.199.14:9327/static/graphs.html?Day

**Comment by Rav3nPL** [comment]
Perfect :)
