### ISSUE TITLE
Graphing error

### ISSUE THREAD

**Issue by wrapperband** [hardcpp/P2PoolExtendedFrontEnd#14]
I have informed p2pool.org, that the graphs become incorrect, when the total hash rate is > 50 MHash/s (say) and the node is 500 KHash/s, the graph for Days and weeks start reporting Zero.
The Hour graphs are correct and you still get paid as the shares go through, the day and week graphs are not correct and the payments aren't shown in the table correctly either, when Total goes over 50 MHash/s. I expect it is a rounding error, as other miners with the same proportion of the total appear to be effected. The attached screen shot graph shows correct at 3 am when the total hash fell below 50 mHash/s
![p2poolgraph1](https://f.cloud.github.com/assets/4609536/661031/eb369990-d725-11e2-9453-69244804d0bb.gif)

**Comment by hardcpp** [comment]
have u a graph called "null" ?

**Comment by wrapperband** [comment]
I don't have a graph called null (on p2pool.org:9377). From what I have seen that is someone mining incorrectly (with no name), or attacking the Pool.

Please note, I think the p2pool payments are correct, but it is the graphs that are are wrong, (when the Total Pool Hash > 100 times the miners rate, the miners Day, week, year graphs go wrong.) I can tell it is the graphs, as they back to being correct (historically), when the total Hash Rate drops bellow 100 \* miner Hash Rate..

**Comment by hardcpp** [comment]
I use same grap lib of the old interface :/
