### ISSUE TITLE
Not paying out

### ISSUE THREAD

**Issue by Petomai** [hardcpp/P2PoolExtendedFrontEnd#15]
This was paying out until after the 17th, now I am getting 0 transactions, I think it's broken. I tried making a new wallet address and using that, it's not working either.

**Comment by hardcpp** [comment]
What is is your crypto name , can i check pool url ?

**Comment by derekslenk** [comment]
It is VERY possible your hashrate is not high enough.  At least with LTC, I would need to maintain over 400khash to keep steady profit.

**Comment by Petomai** [comment]
Thanks for the response, this is for Doubloons on port 8011. it's the 
"not supposed to be serious" cryptocurrency, the first couple days it 
was giving transactions like every couple minutes, now it's been days 
and there hasn't been any. I thought this email/project was for 
Doubloons, sorry if It's not :)

**Comment by Petomai** [comment]
This is my Cgminer batch file
cgminer -o stratum+tcp://p2poolmining.org:8011 -u 
AfpnpHt1c5u7r4eTd7PZKFEeAyf4FsS76v+0.00005821 -p xxxx --scrypt -E 1 -s 1 
-Q 0 --thread-concurrency 8192 --gpu-engine 700 --gpu-memclock 495 
--intensity 13 -w 256 --no-submit-stale --gpu-threads 1 --gpu-powertune 20

it's for the doubloons the cryptocurrency that's just for fun and "not 
to be taken seriously" the first couple days it was sending transactions 
every few minutes, after the 17th it hasn't sent any at all. I tried two 
addresses, neither one worked. The second address was 
AmkSYm9azgCbkZdndMiu1dqk9NVosZV1Ta

Thanks for the reply.

**Comment by Rav3nPL** [comment]
It is NOT front-end issue. Should be closed.
