### ISSUE TITLE
Scale change no workie

### ISSUE THREAD

**Issue by Rav3nPL** [hardcpp/P2PoolExtendedFrontEnd#2]
Clicking on scale: day or another ending with error
on page:
[object Object]
in address:
javascript:period='hour';UpdateData();$('#scale_menu li').removeClass('active');$('#scale1').addClass('active');

**Comment by hardcpp** [comment]
what is your browser

**Comment by hardcpp** [comment]
Tell me if it work on your side

**Comment by Rav3nPL** [comment]
Ok, its done now.
