### ISSUE TITLE
Can't get paid!!!

### ISSUE THREAD

**Issue by sullivanalvarado** [hardcpp/P2PoolExtendedFrontEnd#27]
I know this is not something having to do with the web presentation of the pool, but since the pool has NO way to be contacted, I'm doing this here! 

Please reply as I've just spent the whole day mining, finding blocks and NOTHING has happened. I was listed on the miners page all along under my account: QSg8wTEZUCSPxfJa5pCNgPVRNtiexpkn8m

I'm using Quark CPU miner (minerd_w64_sse4) setting it up using cmd with the pool address. 

Could anyone let me know what is going on? 

Also, donations accepted :-)

thanks a lot in advance

**Comment by JodyPSmith** [comment]
I'm having the same problem, started mining today with the same w64_sse4 cpu miner, I can see my wallet address in the payouts page, if I click it, it shows I have a balance but no indication of when it would be paid out? there are also transactions going out which I'm assuming is a pool fee?

http://176.221.46.81/address/QPL4aeD4FcuYRPgAwAn64C5bL4YVyccEte

Anyway, this was an exchange wallet address, I just changed it to my local wallet and now see an immature balance. Do you have the ID of your wallet or an exchange? The problem might be with the exchange? (I'm using coins-e)

**Comment by sullivanalvarado** [comment]
In my case, there was no transations in my wallet. The exchange would have nothing to do with it because we don't go through any... The pool would simply have to send us quarks directly to our wallet address (QSg8wTEZUCSPxfJa5pCNgPVRNtiexpkn8m is my wallet address) depending on each other's shares.

 According to me, the pool fee would be retained by the pool once the payment is sent from the pool to us.

Could someone help us out? 

Thanks !

**Comment by JoshMPlant** [comment]
This is quite worrisome... I have been mining on p2pool for two days (closer to 60 hours) and only received two tiny payouts on the first day.

Help.... please...

FJuKhf9azpCjMnVMzCBLhiqLkagb1wh3KP
FANCAwVknj6L3yqtEfLUnfFjHAxnsnq7Y2

**Comment by sullivanalvarado** [comment]
And this is obviously profiting the other members of the pool !

**Comment by hardcpp** [comment]
This is a problem for the pool admin not me, my projet is only a "view" of stats not the pool itself

**Comment by sullivanalvarado** [comment]
Could you send us his contact info / email address please? Thanks

**Comment by JodyPSmith** [comment]
he writes code, he doesn't know who the pool op is, whoever is at http://176.221.46.81 didn't change the contact email in the web page, so when we try to contact him the default is still in place.

**Comment by sullivanalvarado** [comment]
So there is just no way. Just changing pool is the solution?

**Comment by hardcpp** [comment]
yes

"Could you send us his contact info / email address please? Thanks" i didnt have it, my project is open source everyone can use it

**Comment by hardcpp** [comment]
i looked the pool, and it seem to be overused, so too much latence and share found are found before in an another p2pool so you dont own the Share this is why you didnt are paid.

The best solution is to install an p2pool instance for your favorite coin at your home : 
- better perf
- 0 fee
