### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by tmagik** [hardcpp/P2PoolExtendedFrontEnd#28]
What is the license.. public domain/mit, or some other license?

I would like to include the human-editable source in https://bitbucket.org/dahozer/catcoin/src/e561b64b8db872ad3916064506f8b3be98354d5a/p2pool/web-static/?at=default but I need to confirm it's compatible with the p2pool GPLv3 license or the project AGPLv3 license.

Thanks!

-- Troy (da hozer/Technomagik)

**Comment by hardcpp** [comment]
They are no really liscence here, you can do what ever you what once you let a link to this github project
