### ISSUE TITLE
Have not gotten paid

### ISSUE THREAD

**Issue by gooniecoin** [hardcpp/P2PoolExtendedFrontEnd#32]
I have not gotten paid for mining GaltCoin (GLT). It was working fine yesterday up until  night time around 11:00PM Eastern Time.

**Comment by bardiharborow** [comment]
This github project is for software that pools run, it isn't actually a pool. You are either referring to GoldMine's pool or my pool. Seeing as my GaltCoin pool last night broke last night, I'll assume you are referring to my pool. My pool is currently experiencing technical difficulties, we aim to have it up and running as soon possible and we will compensate miners.
