### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kalgecin** [hardcpp/P2PoolExtendedFrontEnd#5]
After a few hrs of index being opened, my RAM gets filled up. and the system hangs. This happens on latest chrome browser and latest firefox browser. I'm using ubuntu 13.04.

**Comment by hardcpp** [comment]
Ha i knwon this, due to plot function for charts create some <div> but never delete it, i will fix it soon

**Comment by yrral86** [comment]
So when is soon?  It's been 3 months and the bug is still there.  If I turn off auto refresh it seems to be okay though.  With auto refresh on it eats up 3 GB of ram in a few hours.

**Comment by gwdp** [comment]
+1

**Comment by yrral86** [comment]
This fixes it for me:
https://github.com/hardcpp/P2PoolExtendedFrontEnd/pull/17

For watchers, until this pull is merged, feel free to use my repo:
https://github.com/yrral86/P2PoolExtendedFrontEnd

**Comment by yrral86** [comment]
Update: While my pool request fixes the plotting leak and dramatically improves things, there seems to be another leak somewhere.  Still, auto refresh is manageable now for me if I close the tab once a day or so.
