### ISSUE TITLE
run_p2pool.py

### ISSUE THREAD

**Issue by Gigabear** [hardcpp/P2PoolExtendedFrontEnd#6]
I can´t run python run_p2pool.py on bash. I have win7 python 2.7.4, twisted, Zope 3.8.0, python win32 api, python win32 api wmi wrapper, python-argparse 1.1.

**Comment by hardcpp** [comment]
humm if python installed in c:/

try this
    c:/Python27/python run_p2pool.py

**Comment by hardcpp** [comment]
in a cmd bash or in .bat file
