### ISSUE TITLE
Enable/disable reefresh

### ISSUE THREAD

**Issue by Rav3nPL** [hardcpp/P2PoolExtendedFrontEnd#8]
Auto refresh should be disabled by default, it is draining resources from pool.

**Comment by pawlak2** [comment]
In conjunction with memory leak it also drains browser memory :(

**Comment by hardcpp** [comment]
Any suggestion about how to "display" the choice ?

**Comment by CoRpO** [comment]
![autorefresh](https://f.cloud.github.com/assets/3900969/513107/90afa860-be37-11e2-9f76-32fb56b160ae.png)

```
* Widen the navbar <div> from 440 to ~550px (tested with firefox only)
* Add <li><input type="checkbox" name="autorefresh" /><label for="autorefresh">Auto-refresh</label></li> inside the <ul> scale_menu
* Change css selector ".navbar .nav > li > a" to ".navbar .nav > li > a, .navbar .nav > li > label" to apply correct style to the added text
* Add .navbar .nav > li > input { margin-top: 13px; } to css
* Add .navbar .nav > li > label { padding: 10px 8px 0 17px; float: left;} to css
```

**Comment by hardcpp** [comment]
Can you make an push request ?

**Comment by CoRpO** [comment]
Well a bit of code is not displayed. I'll try to do that, but the JS part will be missing. I'll install git and try to do that

**Comment by hardcpp** [comment]
i will do js part :)

**Comment by CoRpO** [comment]
Did the js part too
