### ISSUE TITLE
Character(Korean) Broken at graphs.html only

### ISSUE THREAD

**Issue by creeras** [hardcpp/P2PoolExtendedFrontEnd#9]
I installe P2PoolExtendedFrontEnd today, 
and wanna change some menu in Korean Language. 

For test, I changed a little bit of .html file. 

Stat page, (index.html) appears well. 
<img src="http://i.imgur.com/8ZbHXl6.png" />

Index page, Korean characters broken. 
<img src="http://i.imgur.com/2O2xHqQ.png" />

Same at Chrome(26.0.1410.64 m), Nightly(23.0a1), IE(10).
In IE 10, 
by (Right Click) - changing Enconding character to Auto or Korean,  it can be fixed easily
<img src="http://i.imgur.com/VQlWnps.png" />

But not at Chrome and Nightly.

Can I see Korean Characters with UTF-8 in graphs.html page?

My p2pool site is 
http://ltckor.tk:9327/static/index.html

Thanks for your work.

**Comment by hardcpp** [comment]
Ok tell me if its working now

**Comment by creeras** [comment]
Do you mean 
change or insert the code "<?xml version="1.0" encoding="UTF-8"?>" at the top of file?

It is already in the file. 
I didn't changed characterset at both html files. It stll remain UTF-8.

But, 
index.html works with Korean char, 
graphs.html doesn't on the other hand.

I erased the line, and copyed(ctrl+c,v) your code. 
In addition, uploaded _thumb.db file also.
But Not fixed yet.

**Comment by creeras** [comment]
Downloaded graphs.html and change some text to korean&upload file again.

It fixed.
Working well with UTF-8.

Good.
Thank you. I love you~

**Comment by hardcpp** [comment]
np :) you are welcome, the change seems be identical but first hidden byte of file is charset, i changed graph.html file encoding to utf8
